name: Build

on:
    push:
      branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Build with Maven
        run: mvn package

      - name: Build docker Image
        run: |
          ls ./target
          docker build -t test:1.0 .