name: Build

on:
    push:
      branches: [ "master" ]

jobs:
  build:

    runs-on: wsl-runner

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'mikhienkov'
          cache: maven
      - name: Build with Maven
        run: mvn -B test --file pom.xml